### ISSUE TITLE
ERROR ILI2DB ORACLE DATABASE -- ERROR EN MODELO DE LEVANTAMIENTO PREDIAL V1.0

### ISSUE THREAD

**Issue by flvgdeveloper** [AgenciaImplementacion/iliSuite#8]
SE PRESENTA EL ERROR EN EL PROCESO DE CREACION DEL MODELO INDICADO EN LA TABLA OW_LADM02.T_ILI2DB_ATTRNAME

info: create table structure, if not existing...
java.io.IOException: failed to add constraint T_INAME_SqlName_Colwner_pkey to table OW_LADM02.T_ILI2DB_ATTRNAME
  failed to add constraint T_INAME_SqlName_Colwner_pkey to table OW_LADM02.T_ILI2DB_ATTRNAME
    ORA-01450: longitud máxima de clave (6398) excedida

LOS DATOS DE CONFIGURACION REMITIDOS FUERON:

--idSeqMax 9999999999999999999 --dropscript C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\borrar.sql --smart2Inheritance --generalTablespace DATOS --dbusr OW_LADM02 --disableNameOptimization --indexTablespace INDX --createFkIdx --createStdCols --createDatasetCol --models ISO19107_PLANAS_V3_0;LADM_COL_V3_0;Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0;Submodelo_Cartografia_Catastral_V1_0;Submodelo_Insumos_Gestor_Catastral_V1_0;Submodelo_Insumos_SNR_V1_0;Submodelo_Integracion_Insumos_V1_0;Sumodelo_Avaluos_V1_0 --createEnumTabsWithId --lobTablespace DATOS --nameByTopic --createNumChecks --strokeArcs --dbschema OW_LADM02 --dbservice xfilesdb.headquarters.com --createGeomIdx --createMetaInfo --createscript C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\crear.sql --coalesceCatalogueRef --coalesceMultiLine --createBasketCol --maxNameLength 30 --createTypeDiscriminator --createUnique --dbpwd ********** --modeldir C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral --beautifyEnumDispName --idSeqMin 1 --schemaimport --createFk --defaultSrsCode 3116 --coalesceMultiSurface

EL LOG DE EJECUCION ES 

--dropscript C:\Projects\borrar.sql --smart2Inheritance --generalTablespace DATOS --dbusr OW_LADM02 --indexTablespace INDX --createFkIdx --createStdCols --createDatasetCol --models ISO19107_PLANAS_V3_0;LADM_COL_V3_0;Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0;Submodelo_Cartografia_Catastral_V1_0;Submodelo_Insumos_Gestor_Catastral_V1_0;Submodelo_Insumos_SNR_V1_0;Submodelo_Integracion_Insumos_V1_0;Sumodelo_Avaluos_V1_0 --createEnumTabsWithId --lobTablespace DATOS --createNumChecks --strokeArcs --dbschema OW_LADM02 --dbservice xfilesdb.headquarters.com --createGeomIdx --createMetaInfo --createscript C:\Projects\crear.sql --coalesceCatalogueRef --coalesceMultiLine --createBasketCol --maxNameLength 30 --createTypeDiscriminator --createUnique --dbpwd ********** --modeldir C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral --beautifyEnumDispName --schemaimport --createFk --defaultSrsCode 3116 --coalesceMultiSurface

Info: dburl <jdbc:oracle:thin:@//localhost:1521/xfilesdb.headquarters.com>
Info: dbusr <OW_LADM02>
Info: ili2ora-4.4.0-773a5a8850fb56d77ac56a8b439cd485196f7789
Info: ili2c-5.0.2-20190906
Info: iox-ili-1.20.16-9bb3c0977717698ff09533f7f6c21ba6e88c81e0
Info: java.version 1.8.0_221
Info: user.name <Fredy>
Info: maxMemory 3704832 KB
Info: currentTime 2020-07-22 14:46:41
Info: dbschema <OW_LADM02>
Info: dburl <jdbc:oracle:thin:@//localhost:1521/xfilesdb.headquarters.com>
Info: dbusr <OW_LADM02>
Info: databaseProduct <Oracle>
Info: databaseVersion <Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production>
Info: driverName <Oracle JDBC driver>
Info: driverVersion <12.1.0.1.0>
Info: compile models...
Info: lookup model <ISO19107_PLANAS_V3_0> in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: lookup model <LADM_COL_V3_0> 2.3 in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: lookup model <Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0> 2.3 in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: lookup model <Submodelo_Cartografia_Catastral_V1_0> 2.3 in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: lookup model <Submodelo_Insumos_Gestor_Catastral_V1_0> 2.3 in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: lookup model <Sumodelo_Avaluos_V1_0> 2.3 in repository <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral/>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\ISO19107_PLANAS_V3_0.ili>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\LADM_COL_V3_0.ili>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\Submodelo_Insumos_V1_0.ili>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_0.ili>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\Submodelo_Avaluos_V1_0.ili>
Info: ilifile <C:\Projects\Catastro\MultipropositoLADM\Catastro_Multiproposito\Levantamiento_Catastral\Submodelo_Cartografia_Catastral_V1_0.ili>
Info: create table structure, if not existing...
java.io.IOException: failed to add constraint T_INAME_SqlName_Colwner_pkey to table OW_LADM02.T_ILI2DB_ATTRNAME
  failed to add constraint T_INAME_SqlName_Colwner_pkey to table OW_LADM02.T_ILI2DB_ATTRNAME
    ORA-01450: longitud máxima de clave (6398) excedida

AGRADEZCO DE ANTEMANO SU PRONTA COLABORACION

**Comment by yesidpol** [comment]
En el log de eventos se encuentra que se produce el siguiente error:

```
ORA-01450: longitud máxima de clave (6398) excedida
```

Este error se presenta porque la llave primaria de la tabla T_ILI2DB_ATTRNAME está excediendo el tamaño máximo de 6398 Bytes. Como la cantidad de caracteres de esa llave primaria es de 2048 (**SqlName**  *varchar2(1024)* y **ColOwner** *varchar2(1024)*)  seguramente la base de datos tiene un conjunto de caracteres que requiere más de un Byte.



Una solución consiste en crear el *table space* de los índices (INDX en la ejecución) con un tamaño de bloque más largo:

```sql
CREATE TABLESPACE INDX
  datafile 'INDX_file' size 1m
  blocksize 16384;
```

y nuevamente se ejecuta el *schema import* en iliSuite.

*Ver más [aquí](https://blogs.oracle.com/sql/how-to-fix-ora-01450-maximum-key-length-6398-exceeded-errors)*

### Nota:

Si al crear el table space con un bloque mayor genera el siguiente error, 

```ORA-29339: tablespace block size 16384 does not match configured block sizes```

el tamaño predeterminado de la cache del bloque de 16K puede estar en 0 y se debe ejecutar lo siguiente para cambiarlo: 

```sql
ALTER system SET db_16k_cache_size = 16m; -- <-- o un tamaño de cache deseado
```

**Comment by flvgdeveloper** [comment]
muchs gracias yecid por tu colaboracion
*_____________________*
*Fredy Varón **García*
Ingeniero Sistemas
Bogotá, Colombia
